# Generated by Django 5.2.12 on 2026-05-28 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiChatSession',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('title', models.CharField(default='新对话', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI 对话会话',
                'verbose_name_plural': 'AI 对话会话',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='aichatmessage',
            name='session',
            field=models.CharField(db_index=True, default='default', max_length=36),
        ),
        migrations.AddField(
            model_name='aichatmessage',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddIndex(
            model_name='aichatmessage',
            index=models.Index(fields=['user', 'session'], name='ai_assistan_user_id_562e9d_idx'),
        ),
        migrations.AddField(
            model_name='aichatsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
